### ISSUE TITLE
補上浮動的 客服

### ISSUE THREAD

**Issue by Wcc723** [KSF2E/f2econf2017#10]
<img width="168" alt="2017-03-27 10 15 52" src="https://cloud.githubusercontent.com/assets/3422575/24360808/f6ffbf68-133a-11e7-99cc-90ff8bdc5095.png">

CSS 可以直接抓六角的
http://www.hexschool.com/

**Comment by unaxie** [comment]
m版時 line 的客服也會出現，所以連帶這個都要上嗎？

**Comment by Wcc723** [comment]
那倒是不用～，至少有一個清楚的即可

**Comment by unaxie** [comment]
有更新惹，在幫看一下會不會怪怪的0.0

**Comment by Wcc723** [comment]
看要不要文字或 icon 其中一個改成白色看看

![2017-03-29 8 26 02](https://cloud.githubusercontent.com/assets/3422575/24433166/73a38a26-1459-11e7-9797-82a3ede9e9e3.png)

![2017-03-29 8 26 20](https://cloud.githubusercontent.com/assets/3422575/24433173/7d0f84c0-1459-11e7-9bc6-1951179835b1.png)
