### ISSUE TITLE
廣告圖設計

### ISSUE THREAD

**Issue by gonsakon** [KSF2E/f2econf2017#15]
@unaxie 
廣告圖需要設計倒數圖示，字數限 20%內，
請在設計上獨立標示出「倒數」樣式，
這廣告圖示會下給已知活動的受眾者，所以已經對活動有大致瞭解的朋友上

設計列表：
1.倒數13~1天各一張
2.12小時、6小時、3小時各一張

**Comment by unaxie** [comment]
https://drive.google.com/open?id=0B8v4KC-V_k8NX3d6OVpTNDhWVkU
放這邊唷
