### ISSUE TITLE
header-L.png 瀏覽上搭配底圖會感覺模糊、不清楚

### ISSUE THREAD

**Issue by gonsakon** [KSF2E/f2econf2017#2]
可能是漸層的關係，導致瀏覽上會有些模糊，
再請看該如何調整

**Comment by Wcc723** [comment]
可能是亮藍色陰影效果讓字比較不清楚

![2017-03-21 3 38 59](https://cloud.githubusercontent.com/assets/3422575/24136952/86c7c580-0e4c-11e7-8b22-2dc542b01b21.png)
