### ISSUE TITLE
價格調整

### ISSUE THREAD

**Issue by Wcc723** [KSF2E/f2econf2017#7]
價格參考(時間可不填)：
http://gonsakon-7655f2.kktix.cc/events/ksf2e

僅限 7 天 - 熱血一般早鳥票	2017/03/26 09:00 ~ 2017/04/03 23:50 
TWD$550

僅限 7 天 - 熱血直播早鳥票 (需有 gmail 帳號)	2017/03/26 09:00 ~ 2017/04/03 23:50 
TWD$500

一般票	2017/04/04 00:00 ~ 2017/05/06 18:00 
TWD$600

直播票 (需有 gmail 帳號)	2017/04/04 00:00 ~ 2017/05/05 00:00 	
TWD$550

個人熱血贊助票 (報名可快速通關)	~ 2017/05/06 18:00	
TWD$1,500

**Comment by unaxie** [comment]
這部分是要放在哪個區塊呢0.0!

**Comment by Wcc723** [comment]
那先不用好了，在討論一下要不要把價錢放上來，先 Close
